networks:
  db-net:
    name: db-net
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=notification-service
    volumes:
      - ./data/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db-net
    restart: unless-stopped
