server:
  port: 8080
spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
notification:
  scheduler:
    dispatch-delay: PT5S    # 5초 설정
